### PR TITLE
Bumping Wiremock version to 2.0.10-beta

### PR DESCRIPTION
**Pull request by adrian-wozniak**

### CODE REVIEW

**Comment by cameleeck** [comment]
+1

**Comment by szpak** [comment]
Are you able to build it locally?
> Unable to load class com.ofg.infrastructure.base.MvcWiremockIntegrationSpec due to missing dependency com/github/tomakehurst/wiremock/client/RemoteMappingBuilder

**Comment by adrian-wozniak** [comment]
Yes, I am. To be sure I removed all Wiremock libraries from my repository caches.

**Comment by mariuszs** [comment]
btw, we should remove stub-runner and wiremock and use accurest stub-runner instead

**Pull request merged**
