### PR TITLE
Broken condition, Swagger requests are always logged

### PR DESCRIPTION
**Pull request by nurkiewicz**

### CODE REVIEW

**Comment by dst** [comment]
+1

**Comment by szpak** [comment]
It fails on Travis. Do you guys plan to do something else with that PR?

**Comment by marcingrzejszczak** [comment]
@nurkiewicz @dst - can we merge this?

**Comment by nurkiewicz** [comment]
Not yet, AFAIR I broke some tests unintentionally, will fix ASAP.

**Comment by marcingrzejszczak** [comment]
@nurkiewicz  @dst Can we merge this?

**Comment by nurkiewicz** [comment]
I promise to merge it over this weekend, sorry.

**Comment by nurkiewicz** [comment]
Changes are ready to be merged.

**Comment by marcingrzejszczak** [comment]
+1

**Pull request merged**
