### PR TITLE
Better http query parameters according to discussion on issue #469 

### PR DESCRIPTION
**Pull request by piotrpietrzak**
Parameters should not contain assignment (equals sign) in case of empty or null values.
"?param is valid"

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
+1

**Comment by piotrpietrzak** [comment]
Please review changes one more time - this time it was done with DSL as proposed in #469

**Comment by dstepanov** [comment]
I would prefer no including empty null parameter value. IMHO you almost never see it being using in the API.

I don't even know if you can match empty parameter value using Accurest, but absent parameter can be matched using ```absent()```.

**Comment by piotrpietrzak** [comment]
Maybe mark this explicit to not change behavior of existing code?
Like this:
.withQueryParameters().parameter("empty","").parameter("removeMe",null).removeEmptyQueryParameters().parameter("addThis",null)

**Comment by dstepanov** [comment]
What existing code, with a map? 

It would be better to ignore null by default and add a third boolean parameter to choose if null value should be kept or not, also from contact point of view there should be a way how to set an empty parameter:

```java
.withQueryParameters()
   .parameter("emptyParam")
   .parameter("xShouldBeRemovedIfNull", x)
   .parameter("yShouldBeKeptIfNull", y, true)
````

WDYT?

**Comment by marcingrzejszczak** [comment]
`.parameter("yShouldBeKeptIfNull", y, true)` this is terrible. 

It will end up with:

`.parameter("yShouldBeKeptIfNull", y, true, false, false, true, true)`

It would be better to have sth like that

```
.withQueryParameters()
   .parameter("emptyParam")
   .parameter("xShouldBeRemovedIfNull", x)
   .parameterWithNullValue("yShouldBeKeptIfNull", y)
```

**Comment by dstepanov** [comment]
Agree

**Comment by piotrpietrzak** [comment]
I think the following _discussion_ will not change this PR. It can be extended/expanded but not changed in current scope - so we can merge this code :) and continue this discussion in better place (#469 is better IMHO). It is better to limit scope of changes with single PR. In this thread we should focus on code review/design of provided solution.

**Comment by marcingrzejszczak** [comment]
Ok so go ahead and merge

**Comment by dstepanov** [comment]
Following discussion can change the behavior introduced in this PR ;)

**Comment by piotrpietrzak** [comment]
How following discussion can change behavior? Or rather - we ageree that we want API exactly like this - adding parameters should act like it was implemented or did I missed something? Another functionalities can be treated as extensions.

**Comment by dstepanov** [comment]
I have suggested that ```parameter``` should ignore null values, right now it doesn't. Do you want to merge it and that change it if we decide to?

**Comment by piotrpietrzak** [comment]
Maybe we should follow principle of least astonishment? If you explicitly add something you expectation is  that this is added. I don't feel default behavior should pretend to be smarter than the user.

**Comment by marcingrzejszczak** [comment]
@piotrpietrzak can you just merge this :) ? BTW where is your super enhanced collaborators view? :)

**Comment by dstepanov** [comment]
No problem with me, I'm just afraid if you merge it and new version is released then we cannot change the default behavior anymore ;)

**Comment by piotrpietrzak** [comment]
@dstepanov Yes you are right - I am afraid that incorrect behavior will become unchangeable. HeadersSetting works exactly like this - I don't think that inconsistent API should be introduced. There are two reasons to not change this behavior (current implementation of similar headers setting and rule of last astonishment - if you add something it should be added). Do you have better arguments to change this?
@marcingrzejszczak this enhanced micro-infra-view is on my 4FinanceIT laptop and on my vacation I did not get it because I have heard that in Spain they steal devices like our laptops iykwim. I will fix new functionality and then I will commit this on github. Do you prefer my account or 4finance near to micro-infra-spring as a micro-infra-view?

**Comment by marcingrzejszczak** [comment]
`micro-infra-view` sounds great :P in the meantime you can push it to your github account somewhere so that we can check it out ;)

**Pull request merged**
