### PR TITLE
remove obsolete changelogs

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by szpak** [comment]
Probably those files are the only place with the history of earlier versions of those modules. Maybe it would be better to add there information that those modules were merged and changelog is available from milestones and keep them for historical purpose?

**Comment by kamilszymanski** [comment]
I thought that all changelogs were moved to releases page during the merge.
I'll add all the necessary links and notes in this PR later in the evening.

**Comment by marcingrzejszczak** [comment]
So what about this PR @kamilszymanski ?

**Comment by kamilszymanski** [comment]
Removed the commit with adding note about projects' origins - it makes no sense after original projects removal.
Nevertheless we should do something with changelogs - either update them (to much hassle imo) or remove them. We should not leave it as is because it is confusing.

**Comment by marcingrzejszczak** [comment]
@szpak - WDYT?

**Comment by szpak** [comment]
I know that I love old stuff and I would preferably do not delete anything anywhere, but why not to put a big info at the beginning of those files that those project were merged and newer history is [...]?

If you don't care about a changelog (at least with names of changes as projects with issue trackers were removed...) then it is also ok for me to remove those files.

**Comment by kamilszymanski** [comment]
In my opinion having changelogs that are not up to date creates unnecessary confusion.

**Comment by szpak** [comment]
Ok, just merge the removal.

**Pull request merged**
