### PR TITLE
Small changes to fix gradle repository problem and minor port clash on tests

### PR DESCRIPTION
**Pull request by piotrpietrzak**
Fixed port clash on tests. Repo added to provide access to spring-cloud-zoookeeper 1.0.0.M1

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@piotrpietrzak can we close this?

**Comment by piotrpietrzak** [comment]
This is small improvement, but what to do with that? Do you want me to merge this?

**Comment by marcingrzejszczak** [comment]
your change doesn't even build... what do you want to merge here?

**Comment by piotrpietrzak** [comment]
right...

**Pull request closed without merging**
