### PR TITLE
New version of swagger

### PR DESCRIPTION
**Pull request by cameleeck**

### CODE REVIEW

**Comment by szpak** [comment]
1. Have you checked it with boot-microservice?
2. What is a relationship between Swagger and Springfox?

**Comment by cameleeck** [comment]
Yep, checked and changed a lot of thinks that changed after migration. Also, repaired tests.
As for Swagger-Springfox relation -> swagger is tool and springfox is a lib that provides Spring integration.

**Comment by szpak** [comment]
+1

**Comment by szpak** [comment]
> Coverage increased (+27.9%) to 73.41%

Nice :)
> The Best Code is No Code At All

**Pull request merged**
