### PR TITLE
test-config: added HttpMockServer constructor with options

### PR DESCRIPTION
**Pull request by sandris-**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Hi Sandris :) 

Thanks so much for the PR!

What's the usecase of this change? You want to customize the HttpMockServer? What was missing in the previous impl?

**Comment by sandris-** [comment]
My first PR on Github :D 

Well I moved integration tests to the test-integration directory in my project and default path for the stubs is defined in WireMockConfiguration as "src/test/resources". I would like to redefine it and since only constructor is accepting port, maybe it is worth to add customization possibility :|

**Comment by marcingrzejszczak** [comment]
Ok. +1 then :) aby objections, anyone?

**Comment by nurkiewicz** [comment]
+1.

2015-10-11 20:31 GMT+02:00 Marcin Grzejszczak <notifications@github.com>:

> Ok. +1 then :) aby objections, anyone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/4finance/micro-infra-spring/pull/506#issuecomment-147233532>
> .
>



-- 
Tomasz Nurkiewicz
http://nurkiewicz.com

**Comment by marcingrzejszczak** [comment]
Congrats on your first PR @sandris- :)

**Comment by marcingrzejszczak** [comment]
@sandris- check out https://github.com/4finance/micro-infra-spring/wiki/Releasing-a-new-version if you want to release a new version

**Comment by sandris-** [comment]
Thank you :)

**Pull request merged**
