### PR TITLE
Use ServiceAlias instead of String when querying by alias

### PR DESCRIPTION
**Pull request by kamilszymanski**
Related to #448

### CODE REVIEW

**Comment by szpak** [comment]
Wouldn't it break all existing applications using those methods?

**Comment by szpak** [comment]
OK, I missed that there were already `@Deprecated` annotation.

**Comment by szpak** [comment]
+1, if our known users are aware of it.

**Comment by kamilszymanski** [comment]
scheduled for version 0.9.0

**Pull request merged**
