### PR TITLE
Rename retry.threads property to rest.client.retry.threads

### PR DESCRIPTION
**Pull request by kamilszymanski**
scheduled for version 0.9.0

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
I'm just wondering if we shouldn't first deprecate the prop before removing it?

**Comment by szpak** [comment]
I was thinking about something similar. Inject both properties and display a deprecation warning if the old is used (if both are used - runtime error?). If we went that way It would be probably good to have a nice and generic implementation to use in other similar places.

**Comment by szpak** [comment]
+1

**Comment by kamilszymanski** [comment]
Since it doesn't break backwards compatibility I'm merging it before v. 0.9.0 release

**Pull request merged**
