### PR TITLE
common directory for module sources

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by szpak** [comment]
Btw, my [fix](https://github.com/groovy/groovy-core/pull/532) was merged and starting with 2.4.2 meta annotations should be supported also in .groovy files.

**Comment by szpak** [comment]
Once again:
> ResourceAccessException: I/O error on GET request for "http://localhost:9573"

We need to investigate that.

**Comment by kamilszymanski** [comment]
Maybe those problems were related to [DDoS attack on GitHub](https://github.com/blog/1981-large-scale-ddos-attack-on-github-com)

Can we merge this PR?

**Comment by szpak** [comment]
If everything works fine, +1.

**Pull request merged**
