### PR TITLE
Tracking code for Travis PR merge builds - DO NOT MERGE

### PR DESCRIPTION
**Pull request by szpak**
# DO NOT MERGE

### CODE REVIEW

**Comment by szpak** [comment]
Btw, any idea about new kind of [errors](https://travis-ci.org/4finance/micro-infra-spring/jobs/56249458#L1012) (excluding DDOS :) )?

```
:test
com.ofg.twitter.places.AcceptanceSpec > should find a place by verifying tweet's geolocation FAILED
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by:
java.lang.IllegalStateException: Could not initialize Logback logging from classpath:logback.groovy
Caused by:
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

Script1.groovy: 6: unable to resolve class com.ofg.infrastructure.property.LogbackConfiguration
@ line 6, column 1.
import com.ofg.infrastructure.property.LogbackConfiguration
^
1 error

java.lang.NullPointerException
```

**Comment by szpak** [comment]
Ok, I made a branch from quite old micro-infra version. There were some changes with Logback in the meantime.

**Comment by dst** [comment]
LogbackConfiguration was introduced around 0.8.14.

**Comment by szpak** [comment]
Unable to reproduce original problem.

**Pull request closed without merging**
