### PR TITLE
Added several improvements to Metrics configuration

### PR DESCRIPTION
**Pull request by nurkiewicz**
This is a follow-up to https://github.com/4finance/micro-infra-spring/pull/135 containing some fixes over original PR.

### CODE REVIEW

**Comment by nurkiewicz** [comment]
@mvaitkus Have a look at https://github.com/4finance/micro-infra-spring/commit/abe09ae307e1c2239eb10dcf3b14b02aff43a500, if it looks fine, I'll merge your changes ASAP.

**Comment by mvaitkus** [comment]
@nurkiewicz sorry for failing tests - I run publishToMavenLocal so I can test built library and it probably didn't execute tests as I didn't notice any failure there.

Your updates look ok and leaving it as TCP with simple format is probably a better option right now as UDP or 2004 port might be blocked in our dev/prod environments. However in the future it would be better to make Pickle format as default as it is more efficient.

**Comment by nurkiewicz** [comment]
@mvaitkus No problem. I need someone to review both yours and mine changes and we'll merge them probably on Monday. They will be part of version [0.8.6](https://github.com/4finance/micro-infra-spring/milestones/0.8.6).

**Comment by nurkiewicz** [comment]
LGTM, I just tried with real Grafana and new metrics look really good. @mchmielarz or @szpak please review as well

**Comment by mchmielarz** [comment]
LGTM

**Pull request merged**
