### PR TITLE
Adding webhook to gitter

### PR DESCRIPTION
**Pull request by marcingrzejszczak**

### CODE REVIEW

**Comment by cameleeck** [comment]
+1

**Comment by szpak** [comment]
Is this channel designed for devs or for users?

**Comment by szpak** [comment]
In the later case maybe only notifications about new releases should be sent?

**Comment by marcingrzejszczak** [comment]
I have no idea who this is for :D

**Comment by szpak** [comment]
Just like Miss Ninja? ;)

**Comment by marcingrzejszczak** [comment]
Let's just merge it :P

**Pull request merged**
