### PR TITLE
spring boot update to 1.2.6

### PR DESCRIPTION
**Pull request by mariuszs**

### CODE REVIEW

**Comment by szpak** [comment]
+1

**Comment by mariuszs** [comment]
Travis suxx

**Comment by marcingrzejszczak** [comment]
Travis suxx, HipChat suxx - everything sucks for you? :P

**Comment by mariuszs** [comment]
fedora roxx

**Comment by mariuszs** [comment]
This builds on JDK7 locally, I dont know what is wrong.

**Comment by szpak** [comment]
Have you [checked](https://solidsoft.wordpress.com/2014/11/19/gradle-tricks-tracking-down-not-expected-transitive-dependencies/) that there is more old servlet-api?

**Comment by szpak** [comment]
Unfortunately it also builds with my HotSpot 1.7.0_72 :(.

**Comment by szpak** [comment]
Maybe our acceptance tests are better than we expected. @mariuszs Have you tried to use micro-infra-spring built with Java 7 in boot-microservice built with Java 8? That the case that fails on Travis.

**Comment by mariuszs** [comment]
No, I havent

**Comment by marcingrzejszczak** [comment]
CAn we merge this?

**Pull request merged**
