### PR TITLE
migrating com.ofg.infrastructure.correlationId to JDK7 

### PR DESCRIPTION
**Pull request by ArturGajowy**
except for the groovy-specific parts

@szpak, @marcingrzejszczak please review :)

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Everything is failing :P

**Comment by jakubnabrdalik** [comment]
ArturGajowy, less joking, more hacking :)

**Comment by szpak** [comment]
@ArturGajowy Have you run that build locally? :)

**Comment by ArturGajowy** [comment]
@jakubnabrdalik same to you ;P

@szpak yep, yet it's not configured to run acceptance spec by default ;>

**Comment by marcingrzejszczak** [comment]
Everything is failing still :/

**Comment by ArturGajowy** [comment]
Sure, the hackathon is over and I didn't have time to sit with it :) Don't
feel urged to merge it yet ;)

**Pull request closed without merging**
