### PR TITLE
Add possibility to configure JVM metrics path base

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by szpak** [comment]
+1

Btw, is there a real life reason to parametrize it, or it is "just in case"?

**Comment by kamilszymanski** [comment]
It's a real need. Client wants to have clear distinction between technical and business metrics and this option allows us to present him how metrics will look like and decide if we should stick to this idea.

**Comment by marcingrzejszczak** [comment]
Please add the property to the list of properties:

https://github.com/4finance/micro-infra-spring/wiki/Configuration

and to the site related to metrics.

**Comment by kamilszymanski** [comment]
Consider it done

**Pull request merged**
