### PR TITLE
Simplify tests with Callable

### PR DESCRIPTION
**Pull request by szpak**
A reminiscence of the latest Warsaw Groovy User Group meeting :).

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Is it really much clearer than previously? Personally, I'm not in favor of maps coerced to classes ;)

**Comment by nurkiewicz** [comment]
I actually give +1 but I love the comment on removed code:

    //Explicit plain old Callable class instead of `{} as Callable`

**Comment by szpak** [comment]
The comment may look strange, but `Callable task = {} as Callable` passed to `submit` (which accepts both `Callable` and `Runnable`) is treated as `Runnable` (as `Closure` implements both those interfaces - the order of choosing proper method is a known "feature" of Groovy). The inline execution works fine.

@marcingrzejszczak Just like me, but that "real" class doesn't look good in Groovy code :).

As sorry about the coverage ;).

**Comment by marcingrzejszczak** [comment]
I don't like it but merge it :P

**Pull request merged**
