### PR TITLE
[#459] Made metrics.path.environment look by default in APP_ENV sys prop

### PR DESCRIPTION
**Pull request by marcingrzejszczak**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@kamilszymanski @szpak @nurkiewicz - anyone? :P

**Comment by nurkiewicz** [comment]
+1. Can we also guess country and service name from `microservice.json`?

**Comment by marcingrzejszczak** [comment]
Sure. 

country == realm
name == by default last chunk of the app path?

**Comment by marcingrzejszczak** [comment]
@nurkiewicz - added those two features

**Comment by marcingrzejszczak** [comment]
@nurkiewicz , @kamilszymanski - if you don't have any suggestions I'll merge this

**Pull request merged**
