### PR TITLE
Use Spec suffix in Spock specifications

### PR DESCRIPTION
**Pull request by dst**
The majority of our Spock specifications has `Spec` suffix in name, so let's be consistent with all specifications.

### CODE REVIEW

**Comment by nurkiewicz** [comment]
You only changed file names, but class names still have `Test` suffix. Besides looks good, I like consistency.

**Comment by dst** [comment]
Great that you have noticed it. I have changed file names from command line.

Now it should be better.

**Comment by szpak** [comment]
> Caused by: org.gradle.api.UncheckedIOException: Could not GET 'https://jcenter.bintray.com/cglib/cglib-nodep/3.1/cglib-nodep-3.1.jar'. Received status code 403 from server: Forbidden

Rerunning tests

**Comment by szpak** [comment]
+1 (if Travis will pass)

**Pull request merged**
