### PR TITLE
upgrade jacoco

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Have you tried to run it together with a Sonar instance?

**Comment by szpak** [comment]
Hmm, is micro-infra code analyzed anywhere with SonarQube? Maybe #313 is obsolete?

**Comment by marcingrzejszczak** [comment]
it's not but it's prepared to be analyzed ;)

**Comment by marcingrzejszczak** [comment]
you can ask here - http://sonarqube.15.x6.nabble.com/SonarQube-Developers-f4523654.html - to add micro-infra-spring to the nemo project - http://nemo.sonarqube.org/

**Comment by szpak** [comment]
I know Nemo, but there is (maybe they changed something?) no control what rules are applied to the project.

**Comment by marcingrzejszczak** [comment]
I don't so I can't say much about this :)

**Comment by kamilszymanski** [comment]
@marcingrzejszczak have not tried to run it with Sonar

**Comment by marcingrzejszczak** [comment]
ok , please merge

**Pull request merged**
