### PR TITLE
[#441] Remote repo is no longer accessed while working offline

### PR DESCRIPTION
**Pull request by marcingrzejszczak**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@adam-wojszczyk , @szpak, @kamilszymanski - review? :)

**Comment by cameleeck** [comment]
It's look good if we use workOffline rather than skipLocalRepo - now it can mislead someone

**Comment by marcingrzejszczak** [comment]
So maybe we can remove the `skipLocalRepo` ? It's deprecated anyway...?

**Comment by cameleeck** [comment]
I think so - its deprecated for about 3 mounths - long time

**Comment by marcingrzejszczak** [comment]
@cameleeck - removed the deprecated API

**Comment by marcingrzejszczak** [comment]
I've f... sth with the removal of API. I'm going to first merge this and then remove the props

**Pull request merged**
